In [1]:
import os
import sys
import session_info
import geopandas as gpd
import numpy as np
import scipy
import pandas as pd
pd.set_option('future.no_silent_downcasting', True)
import matplotlib.pyplot as plt
import mpl_toolkits
import rtree
from shapely.geometry import Polygon

"""
Reads shape data from mid decade redistricting states
Only uses lower 48 states

"""

Shapepath = "Mid_decade_data/"
Dataoutpath ="Process data/"

Projection = "ESRI:102008"
#session_info.show()
print( "Libraries loaded")

Libraries loaded

In [7]:
### Get CA data
File = 'AB604'
Shapedatafile = Shapepath + File + ".shp"
CA_districts = gpd.read_file( Shapedatafile)
CA_districts = CA_districts[['DISTRICT','geometry']]
CA_districts['STATEFP'] = '06'
CA_districts['SESSN'] = 'Mid-decade'
CA_districts['GEOID'] = CA_districts['STATEFP'] + CA_districts['DISTRICT']
CA_districts = CA_districts.reindex(columns=['GEOID','STATEFP','DISTRICT','SESSN','geometry'])
CA_districts.to_crs(Projection, inplace=True)
print('Done')
CA_districts.head()

Done

In [8]:
### Get TX data
File = 'PLANC2333'
Shapedatafile = Shapepath + File + ".shp"
TX_districts = gpd.read_file( Shapedatafile)
TX_districts.rename(columns={'District': 'DISTRICT'}, inplace=True)
TX_districts['DISTRICT'] = TX_districts['DISTRICT'].astype(str).str.zfill(2)
TX_districts['STATEFP'] = '48'
TX_districts['SESSN'] = 'Mid-decade'
TX_districts['GEOID'] = TX_districts['STATEFP'] + TX_districts['DISTRICT'] 
TX_districts = TX_districts.reindex(columns=['GEOID','STATEFP','DISTRICT','SESSN','geometry'])
TX_districts.to_crs(Projection, inplace=True)
print('Done')
TX_districts.head()

Done

,GEOID,STATEFP,DISTRICT,SESSN,geometry
0,4801,48,01,Mid-decade,"POLYGON ((170880.314 -1039996.031, 170707.873 ..."
1,4802,48,02,Mid-decade,"POLYGON ((42971.362 -1183171.43, 42963.142 -11..."
2,4803,48,03,Mid-decade,"POLYGON ((115427.455 -834298.257, 115425.399 -..."
3,4804,48,04,Mid-decade,"POLYGON ((-75172.767 -822150.548, -75169.015 -..."
4,4805,48,05,Mid-decade,"POLYGON ((23692.514 -994759.519, 23700.037 -99..."

In [9]:
### Get NC data
File = 'NC_Congress_2025'
Shapedatafile = Shapepath + File + ".shp"
NC_districts = gpd.read_file( Shapedatafile)
NC_districts = NC_districts[['District','geometry']]
NC_districts.rename(columns={'District': 'DISTRICT'}, inplace=True)
NC_districts['DISTRICT'] = NC_districts['DISTRICT'].astype(str).str.zfill(2)
NC_districts['STATEFP'] = '37'
NC_districts['SESSN'] = 'Mid-decade'
NC_districts['GEOID'] = NC_districts['STATEFP'] + NC_districts['DISTRICT'] 
NC_districts = NC_districts.reindex(columns=['GEOID','STATEFP','DISTRICT','SESSN','geometry'])
NC_districts.to_crs(Projection, inplace=True)
print('Done')
NC_districts.head()

Done

,GEOID,STATEFP,DISTRICT,SESSN,geometry
0,3701,37,01,Mid-decade,"POLYGON ((1630219.175 -462345.23, 1630208.794 ..."
1,3710,37,10,Mid-decade,"POLYGON ((1248324.017 -401182.063, 1248357.573..."
2,3711,37,11,Mid-decade,"POLYGON ((1174185.503 -480628.605, 1174178.989..."
3,3712,37,12,Mid-decade,"POLYGON ((1309559.366 -467263.215, 1309556.061..."
4,3713,37,13,Mid-decade,"POLYGON ((1481545.195 -312820.512, 1481562.918..."

In [10]:
### Get MO data
File = 'HB1_Missouri_Congressional_Districts_2025'
Shapedatafile = Shapepath + File + ".shp"
MO_districts = gpd.read_file( Shapedatafile)
MO_districts = MO_districts[['District','geometry']]
MO_districts.rename(columns={'District': 'DISTRICT'}, inplace=True)
MO_districts['DISTRICT'] = MO_districts['DISTRICT'].astype(str).str.zfill(2)
MO_districts['STATEFP'] = '29'
MO_districts['SESSN'] = 'Mid-decade'
MO_districts['GEOID'] = MO_districts['STATEFP'] + MO_districts['DISTRICT'] 
MO_districts = MO_districts.reindex(columns=['GEOID','STATEFP','DISTRICT','SESSN','geometry'])
MO_districts.to_crs(Projection, inplace=True)
print('Done')
MO_districts.head()

Done

,GEOID,STATEFP,DISTRICT,SESSN,geometry
0,2901,29,01,Mid-decade,"POLYGON ((451732.258 -132503.629, 451794.736 -..."
1,2902,29,02,Mid-decade,"POLYGON ((357324.844 -144568.085, 357332.532 -..."
2,2903,29,03,Mid-decade,"POLYGON ((378930.649 -27785.386, 379044.453 -2..."
3,2904,29,04,Mid-decade,"POLYGON ((329557.002 -227462.58, 329560.991 -2..."
4,2905,29,05,Mid-decade,"POLYGON ((299619.594 -83026.538, 299629.349 -8..."

In [11]:
### Get VA data
File = 'VA cong VA Congressional Proposed - Amended (2026-02-13)'
Shapedatafile = Shapepath + File + ".shp"
VA_districts = gpd.read_file( Shapedatafile)
VA_districts.rename(columns={'district': 'DISTRICT'}, inplace=True)
VA_districts['DISTRICT'] = VA_districts['DISTRICT'].astype(str).str.zfill(2)
VA_districts['STATEFP'] = '51'
VA_districts['SESSN'] = 'Mid-decade'
VA_districts['GEOID'] = VA_districts['STATEFP'] + VA_districts['DISTRICT'] 
VA_districts = VA_districts.reindex(columns=['GEOID','STATEFP','DISTRICT','SESSN','geometry'])
VA_districts.to_crs(Projection, inplace=True)
print('Done')
VA_districts.head()

Done

,GEOID,STATEFP,DISTRICT,SESSN,geometry
0,5101,51,01,Mid-decade,"POLYGON ((1534480.992 -122714.24, 1534447.424 ..."
1,5102,51,02,Mid-decade,"POLYGON ((1600639.223 -230329.425, 1600714.126..."
2,5109,51,09,Mid-decade,"POLYGON ((1292428.963 -243239.493, 1292520.738..."
3,5110,51,10,Mid-decade,"POLYGON ((1508918.508 7838.569, 1508922.123 78..."
4,5111,51,11,Mid-decade,"POLYGON ((1410699.753 -45157.441, 1410644.753 ..."

In [12]:
### Get FL data
File = 'EOGPCRP2026'
Shapedatafile = Shapepath + File + ".shp"
FL_districts = gpd.read_file( Shapedatafile)
FL_districts['DISTRICT'] = FL_districts['DISTRICT'].astype(str).str.zfill(2)
FL_districts['STATEFP'] = '12'
FL_districts['SESSN'] = 'Mid-decade'
FL_districts['GEOID'] = FL_districts['STATEFP'] + FL_districts['DISTRICT'] 
FL_districts = FL_districts.reindex(columns=['GEOID','STATEFP','DISTRICT','SESSN','geometry'])
FL_districts.to_crs(Projection, inplace=True)
print('Done')
FL_districts.head()

Done

,GEOID,STATEFP,DISTRICT,SESSN,geometry
0,1201,12,01,Mid-decade,"POLYGON ((841714.659 -1012583.627, 842405.958 ..."
1,1202,12,02,Mid-decade,"POLYGON ((902860.619 -1036981.359, 902858.828 ..."
2,1203,12,03,Mid-decade,"POLYGON ((1179726.068 -1044308.727, 1179719.21..."
3,1204,12,04,Mid-decade,"POLYGON ((1319260.541 -1046909.143, 1319247.11..."
4,1205,12,05,Mid-decade,"POLYGON ((1361921.195 -1081139.031, 1361895.34..."

In [13]:
#### Combine and save file for further processing
Dfs = [CA_districts,TX_districts,NC_districts,MO_districts,VA_districts, FL_districts]
Mid_decade_districts = pd.concat( Dfs, ignore_index=True)
Shapeoutfile = Dataoutpath + 'Mid_decade'  + ".shp"
Mid_decade_districts.to_file( Shapeoutfile )
print( 'Done writing ', len( Mid_decade_districts ), 'rows to ', Shapeoutfile)

Done writing  151 rows to  Process data/Mid_decade.shp